### ISSUE TITLE
Demo site for ezPlus broken

### ISSUE THREAD

**Issue by ParkerD13** [igorlino/elevatezoom-plus#104]
Hi, your demo site at https://igorlino.github.io/elevatezoom-plus/examples.htm seems to be broken. For mit in FF dev.ed. and in Chrome.

**Comment by igorlino** [comment]
@ParkerD13 thanks for informing , the linking of the libraries had to be changed from http to https. Now its all loading properly.

Press CTRL+F5 to reload the page while cleaning the cache.
