### ISSUE TITLE
Expected an assignment or function call and instead saw an expression

### ISSUE THREAD

**Issue by jsmad** [igorlino/elevatezoom-plus#11]
While minifying the script, I got an error at line 545 about a missing name after . operator, which led me to run jshint on the script, which in turn produced the following error, again at line 545:

```
jquery.ez-plus.js: line 545, col 18, Expected an assignment or function call and instead saw an expression.

1 error
```

The offending line is:
```javascript
self.delete;
```

I see no reason why it should be there, so I've removed it.

**Comment by igorlino** [comment]
mmm, I don't know that delete would mean.... (perhaps a typo while code-thinking)  But seems pretty safe to remove.

**Comment by igorlino** [comment]
done
