### ISSUE TITLE
Invalid CSS "px solid", border not effective on "inner" zoomType

### ISSUE THREAD

**Issue by jsmad** [igorlino/elevatezoom-plus#12]
I noticed that the function getInnerZoomStyle() in line 198 contains invalid CSS:

```javascript
'px solid ' + self.options.borderColour + ';' +
```

Obviously, there is something missing, I also noticed that a similar function for zoomType "window" contains a border, so I suppose a copy/paste went bad at some point.

The line 198 should probably look like this:

```javascript
'border: ' + String(self.options.borderSize) + 'px solid ' + self.options.borderColour + ';' +
```

Now, you get a proper border set based on the borderSize parameter and properly coloured based on the borderColour parameter.

**Comment by igorlino** [comment]
Hi, great!.  Do you want to create a PR or should I put it ?  (PR are most welcome, even if small)

**Comment by jsmad** [comment]
Please open one yourself if possible, thank you.

**Comment by igorlino** [comment]
oh well, I love seen PRs from others.
Its already committed: https://github.com/igorlino/elevatezoom-plus/commit/a71c2c125643aaef8e0bb1222f238daa4a305a2e
