### ISSUE TITLE
ezPlus with multiple images

### ISSUE THREAD

**Issue by volkerdobler** [igorlino/elevatezoom-plus#120]
I have problems using ezPlus with multiple images on my page.
I have nailed down the problem to line 320 in (current) version 1.2.4

`"$('.' + self.options.container).remove();`

If this line exist, all (previous added) classes are removed and only the last image-container stays.
Why is this line in the script?

If I run the script with this line, and I have 2+ pictures I would like to zoom (e.g. `$('#pic1').ezPlus(); $('#pic2').ezPlus();`), the container for the first pic (#pic1) is removed with the second image and therefore I am not able to zoom the image #pic1.

To run both images I have to add at least the "ZoomContainer" option with different values - which is not what I expected (e.g. `$('#pic1').ezPlus({ZoomContainer:a}); $('#pic2').ezPlus({ZoomContainer:b}`); will work). But this is complicated and I would like to run multiple images with the standard settings (if possible :-) )

Can I (safety) remove this line? What is the purpose of this line?

**Comment by vaajnur** [comment]
same problem on multiple images

**Comment by vaajnur** [comment]
after comment this 
"$('.' + self.options.container).remove();
all images are work!
volkerdobler,  thank you!

**Comment by mgcastelberg** [comment]
Excelent info my friend

**Comment by alexandregyn** [comment]
> depois de comentar isso
> "$ ('.' + self.options.container) .remove ();
> todas as imagens são funcionais!
> volkerdobler, obrigado!

Thanks very good friend that your information

**Comment by igorlino** [comment]
thanks @volkerdobler  for the fix :)
