### ISSUE TITLE
loading icon/spinner placement and hide

### ISSUE THREAD

**Issue by jsmad** [igorlino/elevatezoom-plus#13]
I found two issues that affect my "inner" zoomType code.

1) The loading icon (spinner) does not appear on top of the image, instead it appears below. I had to add "top:0px;" to line 1278, for proper placement.

2) After switching between gallery images for several times, multiple loading icons appear underneath the images while they load. It seems like they are never removed. The line 1279 creates loading icons, but they are never remove()'ed from the DOM, they are only hidden at line 1490. To fix this, I added a class to the loading icon object, and use .remove() within donecallback.

**Comment by igorlino** [comment]
Hi again, I have not really use the gallery besides the demo example, but the corrections makes sense, would you also like to create a PR?

**Comment by igorlino** [comment]
I have added the code for the issue 1, and add a class for issue 2.
Please take a look a the commit: https://github.com/igorlino/elevatezoom-plus/commit/81a98a76520571da0fd0cbae5741048321a608f7

Could you please point where you are adding the jquery remove ? (the line and and its code)
