### ISSUE TITLE
Add id tag to .zoomContainer

### ISSUE THREAD

**Issue by igorlino** [igorlino/elevatezoom-plus#16]
source: https://github.com/elevateweb/elevatezoom/pull/118

It adds {image#id}-zoomContainer id to the new .zoomContainer elements.
It allows to completely remove an elevateZoom associated to an image with id tag, by selecting the zoomContainer associated to an image with the id selector.
This is crucial for multi elevateZoom images in carousels, where the image moves and the zoomContainer was covering elements on the page.

**Comment by miqmago** [comment]
Do you plan to make a release to bower? Actually it downloads 2.2.3

**Comment by igorlino** [comment]
@miqmago I think you mix up projects.

The version 2,2,3 is from 'elevatezoom', which is the predecessor of this project.

The elevatezoom-plus (ezp), is up-to-date with version 1.2.0
see https://github.com/igorlino/elevatezoom-plus/blob/master/CHANGELOG.md

The proper way to reference it in bower should like this:

"dependencies": {
"ez-plus": "~1.2.0"
}

Thats it. :+1:
