### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by oagarcia** [igorlino/elevatezoom-plus#2]
Running:
`npm install elevatezoom-plus` or `npm install angular-ez-plus` throws an error indicating that such components are not part of the npm registry... Actually those are not available on https://www.npmjs.com

**Comment by igorlino** [comment]
You totally right. :)

Now they are registered. (I myself only use bower, so I forgot to register the modules)

**Comment by igorlino** [comment]
Please tell me if that works. I don't have an npm workflow (only bower).  PR are also welcome.

**Comment by igorlino** [comment]
Ok, I have tried locally, the readme.MD had an outdated id.
It should be:

`npm install ez-plus`

**Comment by oagarcia** [comment]
Sorry for the too late response... even as it is closed: It works :)

**Comment by igorlino** [comment]
Sure no problem :+1:
