### ISSUE TITLE
Needs Double Tap on Touch Devices

### ISSUE THREAD

**Issue by st11x** [igorlino/elevatezoom-plus#23]
When you are either on the mobile emulator or an active touch device, you need to tap twice to launch the zoom. 

You can see this on every example on http://igorlino.github.io/elevatezoom-plus/examples.htm except for the one with the tint.

I have tracked it down and only if you set tint=true will it work properly.

**Comment by igorlino** [comment]
Thanks, I will take a look with my tablet.
