### ISSUE TITLE
Options zoomWindowOffetx??

### ISSUE THREAD

**Issue by merrickfox** [igorlino/elevatezoom-plus#3]
For some reason, the documentation (in both the examples and API) specifies using the property "zoomWindowOffetx" for offsets on the x-axis, this property doesn't actually exist and instead you need to use "zoomWindowOffsetX", might be worth updating the documentation?

**Comment by igorlino** [comment]
yeah your are right. Originally it actually was zoomWindowOffetx
I decided in the code to use the better naming, but the latest demo had the old stuff still.

Its now fixed with the latest commit. Thanks.
