### ISSUE TITLE
Minify

### ISSUE THREAD

**Issue by daverogers** [igorlino/elevatezoom-plus#34]
It would be a good idea to repo the /dist folder with minified files. This makes it lighter to consume via CDN.

**Comment by igorlino** [comment]
Yes that makes sense. Will do it today in the evening.

**Comment by igorlino** [comment]
MMM seems i broke my promise.... Totally forgot about it. I will try create a new version during these week.

**Comment by daverogers** [comment]
haha it's cool. I know how it goes with open source projects ;)

**Comment by igorlino** [comment]
Yeah its done!!! I managed to remember today.
Have fun !

**Comment by igorlino** [comment]
For production use you can use:

<script type="text/javascript" src="https://cdn.rawgit.com/igorlino/elevatezoom-plus/1.1.20/dist/jquery.ez-plus.min.js"></script>

<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/igorlino/elevatezoom-plus/1.1.20/css/jquery.ez-plus.css" media="screen" />


Cheers
