### ISSUE TITLE
Destroy doesn't remove gallery binding

### ISSUE THREAD

**Issue by entr** [igorlino/elevatezoom-plus#37]
That's pretty much it. After calling `.data('ezPlus').destroy()` clicks on gallery items still update zoom image.

**Comment by goldnuggets24** [comment]
Yup. Would be amazing to have a 'destroy' method with this plugin that works. Besides that, it works great. This is a bit of a dealbreaker though unfortunately. I imagine it would be a simple thing to add?

**Comment by igorlino** [comment]
Yes makes sense.

Due to a terrible lack of time, i'm not doing much bugfixes at the moment unless the are related to my project.

PR are welcome, if any of you wish to help out.
