### ISSUE TITLE
Internet Explorer: Number.isInteger not defined

### ISSUE THREAD

**Issue by damianroszyk** [igorlino/elevatezoom-plus#43]
https://github.com/igorlino/elevatezoom-plus/blob/master/src/jquery.ez-plus.js#L1119

reference: http://caniuse.com/#feat=es6-number
maybe a polyfill for this issue ?

**Comment by sergeh** [comment]
adding this polyfill fixes the issue

```
Number.isInteger = Number.isInteger || function(value) {
    return typeof value === "number" &&
           isFinite(value) &&
           Math.floor(value) === value;
};
```
