### ISSUE TITLE
CDN is not working

### ISSUE THREAD

**Issue by gauravojha** [igorlino/elevatezoom-plus#44]
Cant use the CDN [https://cdn.rawgit.com/igorlino/elevatezoom-plus/1.1.20/dist/jquery.ez-plus.min.js]

404 Not Found

**Comment by boarnoah** [comment]
1.1.20 doesn't come with a [minifed version](https://github.com/igorlino/elevatezoom-plus/tree/1.1.20/src).Google [closure compiler](https://closure-compiler.appspot.com/home) generates a working copy at simple settings

**Comment by igorlino** [comment]
Sorry, was overbusywithout computer lately, Your commit has been now merged.

Thanks all of you. It's really nice to see improvements & fixes coming to this project.
