### ISSUE TITLE
dependency missing on grunt wiredep

### ISSUE THREAD

**Issue by finzero** [igorlino/elevatezoom-plus#47]
Hello,

thanks for this great plugin.
i having a trouble when i'm using grunt wiredep on angular apps, the jquery.ez-plus.js not injected into my index.html.
After further investigation i found that you have
```
"main": [
        "dist/jquery.ez-plus.js",
        "css/jquery.ez-plus.css"
 ],
```
in your bower.json file, you set the jquery file on 'dist' folder while you have it on 'src' folder.
Edit: (i solved this issue by changing the 'dist' to 'src' in the bower json, but just in case other people have the same trouble) 

Thank You,

**Comment by Ivorius** [comment]
Yes me too.

**Comment by igorlino** [comment]
interesting, i use gulp wiredep and the injection works fine.
