### ISSUE TITLE
Zoom Issues

### ISSUE THREAD

**Issue by reinierkors** [igorlino/elevatezoom-plus#54]
So when using the plugin with default settings, it will fit the whole image, and not zoom the large image:

![gallery](http://i.imgur.com/1USd06w.png)

Original images:
![small](https://cdn.shopify.com/s/files/1/1468/7652/products/product-image-18719247_large.jpg?v=1472995244)
![large](https://cdn.shopify.com/s/files/1/1468/7652/products/product-image-18719247_1024x1024.jpg?v=1472995244)

If anyone knows how to fix this, it's working fine on some larger images:
![working](http://i.imgur.com/qNG8F3P.png)

**Comment by harlet** [comment]
Maybe is a CSS problem?
