### ISSUE TITLE
Zoom container width and height not set in lens mode on re-size

### ISSUE THREAD

**Issue by dscook** [igorlino/elevatezoom-plus#6]
We're finding ez-plus adds some good functionality to our site.

We've noticed that when the browser starts off small and is re-sized to a larger size, the left and top positions of the zoom container are recalculated correctly in responsive mode.  However the width and height of the container are not re-calculated so it remains of a small size.

Amending the code to the following appears to fix the problem:

            //container fix
            self.zoomContainer.css({
                top: self.nzOffset.top,
                left: self.nzOffset.left,
                width: self.nzWidth,  // new code
                height: self.nzHeight // new code
            });

**Comment by igorlino** [comment]
Thats would be a new feature. 

I have added a responsive demo. (see the last example of the examples page)
So far I have used CSS rules to drive the behaviour.

Your seems interesting, but I would probably make it optional.

Activating that change, when for example, 'zoomResponsive' : true,

we already have (responsive : true) but thats of different nature.

Please create a PR.

**Comment by st11x** [comment]
@dscook I find that your fix also addresses another problem. I had these configs for a gallery of images:

          zoomType: 'lens'
          lensShape: 'round'
          containLensZoom: true

If the images have different widths, the the containLensZoom doesn't work properly unless I apply your fix.

**Comment by igorlino** [comment]
@dscook thanks for the code fix
@st11x thanks for the feedback

I will make a release now.
