### ISSUE TITLE
package.json file was not updated on tag release

### ISSUE THREAD

**Issue by dvdvck** [igorlino/elevatezoom-plus#67]
Hi there,

At comit 0d408d5fe5a08862522af3aa1bfe1c2166fe9d8d there was a minor bump version from 1.1.20 to 1.2.0. The package.json file was not updated to reflect this version.

This makes an error when https://github.com/igorlino/angular-elevatezoom-plus package is installed from npm using 1.2.0 version.

**Comment by igorlino** [comment]
Thanks!

**Comment by igorlino** [comment]
Gracias!, Tambien he actualizado las version el registro de NPM. (para que aparezca como la version oficial)
