### ISSUE TITLE
How to destroy this zoom?

### ISSUE THREAD

**Issue by kotakorange** [igorlino/elevatezoom-plus#7]
because I load this script on modal, so I need to destroy it when the modal is closed.

**Comment by igorlino** [comment]
Calling the method destroy before closing ther modal.

var action='hide';
var plugin = $(element).data('ezPlus');
                if (plugin) {
                    plugin.showHideZoomContainer(action);
                    plugin.showHideWindow(action);
                    plugin.showHideTint(action);
                    plugin.showHideLens(action);

                    plugin.destroy();
                }

**Comment by daverogers** [comment]
why doesn't `.destroy()` just run `.showHideWindow('hide')` (etc.) itself? the whole idea of destroy is to, well, destroy :facepunch:
