### ISSUE TITLE
Zoom size check bug

### ISSUE THREAD

**Issue by jmarceli** [igorlino/elevatezoom-plus#9]
Zoom size defined with `minZoomLevel` and `maxZoomLevel` is checked after size changes but should be checked **before**.

EXAMPLE:

config:

    minZoomLevel:  1
    maxZoomLevel: 3

results in:

    minZoomLevel: 0.9
    maxZoomLevel: 3.1

This is not a problem unless you use `scrollZoomIncrement` option with higher value like `2` or `3`.

**Comment by igorlino** [comment]
@jmarceli  is this still an issue ?

**Comment by jmarceli** [comment]
I've made an update and bug is still there. These are my settings (in CoffeeScript):

    $(@).ezPlus
      scrollZoom: true
      zoomLevel: 2.5
      minZoomLevel: 1.5
      maxZoomLevel: 2.5
      # buggy because it checks zoom size after resizing not BEFORE
      scrollZoomIncrement: 0.5
      responsive: true
      zoomWindowHeight: 430
      zoomWindowWidth: 430
      borderSize: 0
      lensBorderSize: 0

I was trying to track down and fix this bug but without any luck. I think that it is somewhere in the lines 1725-1768 but I'm not sure.

**Comment by jmarceli** [comment]
I've manage to fix this issue. Please review my PR https://github.com/igorlino/elevatezoom-plus/pull/22

**Comment by igorlino** [comment]
Great, looks good to me :+1:
